version: '3.4'

services:
  tuya_mqtt.net:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build:
      context: .
      dockerfile: ./tuya_mqtt.net/Dockerfile.dev
    ports:
      - "80"
