name: Docker Image CI
env:
  IMAGE_NAME: volkerhaensel/${{ github.event.repository.name }}
  REGISTRY: docker.io
on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build  Docker image
      uses: docker/build-push-action@v4
      with:
          context: ./tuya_mqtt.net
          platforms: linux/amd64
          tags: ${{ steps.date.outputs.date }}
          push:  false
          cache-from: type=gha
          cache-to: type=gha,mode=max
